### ISSUE TITLE
Corporate Monobank open API > Init

### ISSUE THREAD

**Issue by vergilet** [vergilet/monobank#5]
https://api.monobank.ua/docs/corporate.html

**Comment by dreyks** [comment]
I've implemented corp api in a branch of my fork https://github.com/dreyks/monobank/tree/corp-api
I haven't battle-tested it yet, but if you're interested we can sync, I've been looking for you in the Monobank API telegram channel :D

**Comment by vergilet** [comment]
Hey @dreyks !

Thanks for diving into the corp API and for reaching out! Your fork looks promising. 🚀
I'm swamped at the moment and not very active in the Monobank API Telegram or on GitHub. However, I'm keen on what you're doing.

Could you do some battle testing on your end and throw in some RSpec tests if possible? That would help a ton. Once you're ready, hit me up with a pull request. I'll do my best to check it out and merge it as soon as I can.

Really appreciate your effort and looking forward to seeing your changes in action!

**Comment by dreyks** [comment]
👍 

I've already sent a corp api access request through my corp-api code. When it gets accepted I'll start using it in my pet-project and we'll see if it works :D 

the specs are already there, both for corp and non-corp apis

I'll make a draft PR today

**Comment by vergilet** [comment]
@dreyks gem is published - https://rubygems.org/gems/monobank and as release https://github.com/vergilet/monobank/releases

Pleasy try to verify if gem build is sufficient. 

And feel free to close this issue.
Thanks again 😃

**Comment by dreyks** [comment]
yup. switched to upstream, everything seems to work :)
